routes/web.php
<?php

use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\PositionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});
Route::resource('position',PositionController::class);
Route::resource('employee',EmployeeController::class);

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;
    protected $fillable = [
        'name_employee',
        'nip',
        'position_id',
        'departemen',
        'date_of_birth',
        'year_of_birth',
        'alamat',
        'no_telp',
        'agama',
        'status',
        'foto_ktp'
    ];

    public function relasi_position()
    {
        return $this->belongsTo(Position::class, 'position_id', 'id');
    }
}

app/Models/Position.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Position extends Model
{
    use HasFactory;
    protected $fillable = [
        'name'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Api/GetPosition.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Position;
use Illuminate\Http\Request;

class GetPosition extends Controller
{
    public function index()
    {
        return Position::all();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use App\Models\Position;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (request()->ajax()) {
            $queryEmployees = Employee::with([
                'relasi_position'
            ])->latest()->get();
            return datatables($queryEmployees)
                ->addColumn(
                    'action',
                    function ($data) {
                        $btnAction = '<a href="#" class="btn btn-warning mb-3" id="btn-edit" data-id="' . $data->id . '" title="Edit Data"> Edit</a>';
                        $btnAction .= '<br>';
                        $btnAction .= '<a href="#" class="btn btn-info mb-3" id="btn-show" data-id="' . $data->id . '" title="Show Data"> Show</a>';
                        $btnAction .= '<br>';
                        $btnAction .= '<a href="#" id="btn-delete" class="btn btn-danger" data-id="' . $data->id . '" title="Hapus Data"> Hapus</a>';
                        return $btnAction;
                    }
                )
                ->rawColumns([
                    'action'
                ])
                ->addIndexColumn()
                ->make(true);
        }
        return view('employee');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = Position::all();
        return view('create-employee', [
            'data' => $data
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $messages = [
            'required' => ':attribute wajib diisi cuy!!!',
            'unique' => ':attribute sudah ada',
        ];

        $this->validate($request, [
            'nip' => 'required|min:5|unique:employees,nip',
        ], $messages);
        Employee::create($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        //
    }
}

app/Http/Controllers/PositionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Position;
use Illuminate\Http\Request;

class PositionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (request()->ajax()) {
            $positions = Position::all();
            return datatables($positions)
                ->addIndexColumn()
                ->toJson();
        }
        return view('position');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function show(Position $position)
    {
        return Position::all();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function edit(Position $position)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Position $position)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function destroy(Position $position)
    {
        //
    }
}

resources/views/create-employee.blade.php
@extends('layout.app')

@section('css')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
@endsection
@section('breadcrumb')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Karyawan</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Karyawan</li>
    </ol>
</div>
@endsection
@section('content')
@if (count($errors) > 0)
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<div class="card sm mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary"></h6>

    </div>
    <div class="card-body">
        <form action="{{ route('employee.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-md-6">
                    <label class="control-label">
                        NIP
                    </label>
                    <input class="form-control form-white" type="text" name="nip" id="nip" required />
                </div>
                <div class="col-md-6">
                    <label class="control-label">
                        Nama Karyawan
                    </label>
                    <input class="form-control form-white" type="text" name="name_employee" id="name_employee"
                        required />
                </div>
                <div class="col-md-6">
                    <label class="control-label">
                        Jabatan
                    </label>
                    <select class="form-control" name="position_id" style="width: 100%;" id="position_id">
                        <option selected disabled>---</option>
                        @foreach ($data as $d)
                        <option value="{{ $d->id }}">{{ $d->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-md-6">
                    <label class="control-label">
                        Departemen
                    </label>
                    <input class="form-control form-white" type="text" name="departemen" id="departemen" required />
                </div>
                <div class="col-md-6">
                    <label class="control-label">
                        Tanggal lahir
                    </label>
                    <input class="form-control form-white" type="date" name="date_of_birth" id="date_of_birth"
                        required />
                </div>
                <div class="col-md-6">
                    <label class="control-label">
                        Tahun lahir
                    </label>
                    <select class="form-control" name="year_of_birth" id="year_of_birth" required>

                    </select>
                </div>
                <div class="col-md-6">
                    <label class="control-label">
                        Alamat
                    </label>
                    <input class="form-control form-white" type="text" name="alamat" id="alamat" required />
                </div>
                <div class="col-md-6">
                    <label class="control-label">
                        No Telp
                    </label>
                    <input class="form-control form-white" name="no_telp" id="no_telp" type="number"
                        ondrop="return false;" onpaste="return false;"
                        onkeypress="return event.charCode>=48 && event.charCode<=57" required />
                </div>
                <div class="col-md-6">
                    <label class="control-label">Agama</label>
                    <div class="row">
                        <div class="col-1">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="agama" id="agama1">
                                <label class="form-check-label" for="agama1">
                                    Islam
                                </label>
                            </div>
                        </div>
                        <div class="col-1">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="agama" id="agama2">
                                <label class="form-check-label" for="agama2">
                                    Katolik
                                </label>
                            </div>
                        </div>
                        <div class="col-1">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="agama" id="agama3">
                                <label class="form-check-label" for="agama2">
                                    Protestan
                                </label>
                            </div>
                        </div>
                        <div class="col-1">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="agama" id="agama3">
                                <label class="form-check-label" for="agama3">
                                    Hindu
                                </label>
                            </div>
                        </div>
                        <div class="col-1">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="agama" id="agama4">
                                <label class="form-check-label" for="agama4">
                                    Budha
                                </label>
                            </div>
                        </div>
                        <div class="col-1">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="agama" id="agama5">
                                <label class="form-check-label" for="agama5">
                                    Konghuchu
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <label class="control-label">
                        Status
                    </label>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" id="status1" value="1" name="status">
                        <label class="form-check-label" for="status1">
                            Aktif
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" id="status2" value="0" name="status">
                        <label class="form-check-label" for="status2">
                            Tidak Aktif
                        </label>
                    </div>
                </div>
                <div class="col-md-12">
                    <label class="control-label">
                        File KTP
                    </label>
                    <input type="file" name="foto_ktp" id="foto_ktp" class="form-control">
                </div>
                <div class="col-md-12 mt-5">
                    <button type="submit" class="btn btn-primary w-100">SIMPAN DATA</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

@push('js')
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function() {

            $.get('{{ url('api/get-position') }}', function(data) {
                var trPositon = '<option></option>';
                $.each(data, function(i, post) {
                    trPositon += '<option value="' + post.id + '">' + post
                        .name + '</option>';
                })
                $('#position_id').empty().append(trPositon);
            })

            var start = 1900;
            var end = new Date().getFullYear();
            var options = "<option disabled selected>---</option>";
            for (var year = start; year <= end; year++) {
                options += "<option value=" + year + ">" + year + "</option>";
            }
            document.getElementById("year_of_birth").innerHTML = options;
        })
</script>
<script>
    $(function() {
            $('#only-number').on('keydown', '#number', function(e) {
                -1 !== $
                    .inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) || /65|67|86|88/
                    .test(e.keyCode) && (!0 === e.ctrlKey || !0 === e.metaKey) ||
                    35 <= e.keyCode && 40 >= e.keyCode || (e.shiftKey || 48 > e.keyCode || 57 < e
                    .keyCode) && (96 > e.keyCode || 105 < script e.keyCode) && e.preventDefault()
            });
        })
</script>
@endpush

resources/views/employee.blade.php
@extends('layout.app')

@section('css')
<link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('breadcrumb')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Karyawan</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Karyawan</li>
    </ol>
</div>
@endsection
@section('content')
<div class="card sm mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary"></h6>
    </div>
    <div class="card-body">
        <a href="{{ route('employee.create') }}" id="add" class="btn btn-primary">+ Tambah Data</a>
        <div class="table-responsive p-3">
            <table class="table align-items-center table-flush" id="dataTableEmployee">
                <thead class="thead-light">
                    <tr>
                        <th>No</th>
                        <th>NIP</th>
                        <th>Posisi</th>
                        <th>Nama</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>


{{-- Modal --}}
{{-- Add --}}
<div class="modal fade none-border" id="addModal">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5><strong>Tambah Data</strong></h5>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                <form id="form-add">
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <label class="control-label">
                                Nama Karyawan
                            </label>
                            <input class="form-control form-white" type="text" name="nama_barang" id="nama_barang_acc"
                                required />
                        </div>
                        <div class="col-md-6">
                            <label class="control-label">
                                Harga Beli
                            </label>
                            <input class="form-control form-white" type="number" name="harga_beli" id="harga_beli_acc"
                                required />
                        </div>
                        <div class="col-md-6">
                            <label class="control-label">
                                Harga Jual
                            </label>
                            <input class="form-control form-white" type="number" name="harga_jual" id="harga_jual_acc"
                                required />
                        </div>
                        <div class="col-md-6">
                            <label class="control-label">
                                Merk
                            </label>
                            <input class="form-control form-white" type="text" name="merk" id="merk_acc" />
                        </div>
                        <div class="col-md-6">
                            <label class="control-label">
                                Stok
                            </label>
                            <input class="form-control form-white" type="number" name="stok_barang" id="stok_barang_acc"
                                required />
                        </div>
                        <div class="col-md-6">
                            <label class="control-label">
                                Supplier
                            </label>
                            <select class="js-example-basic-single" name="supplier_id" style="width: 100%;"
                                id="supplier_idAdd">

                            </select>
                        </div>
                        <div class="col-md-6">
                            <label class="control-label">
                                Kategori
                            </label>
                            <select class="js-example-basic-single" name="kategori_id" style="width: 100%;"
                                id="kategori_idAdd">

                            </select>
                        </div>
                        <div class="col-md-6">
                            <label class="control-label">
                                Satuan
                            </label>
                            <select class="js-example-basic-single" name="satuan_id" style="width: 100%;"
                                id="satuan_idAdd">

                            </select>
                        </div>
                        <div class="col-md-6">
                            <label class="control-label">
                                Diskon
                            </label>
                            <input class="form-control form-white" type="number" name="diskon" id="diskon_acc" />
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Close</button>

                <button id="btn-submit" type="button" class="btn btn-success waves-effect waves-light save-category"
                    data-dismiss="modal" onclick="addPost()">Simpan</button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')
{{-- <script src="https://code.jquery.com/jquery-3.6.0.js"
    integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script> --}}
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script>
    $('#dataTableEmployee').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('employee.index') }}",
            columns: [{
                    data: 'DT_RowIndex',
                    orderable: false,
                    searchable: false,
                    className: "text-center"
                },
                {
                    data: 'nip'
                },
                {
                    data: 'relasi_position.name'
                },
                {
                    data: 'name_employee'
                },
                {
                    data: 'action'
                },
            ]
        })
</script>
@endpush

resources/views/layout/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="img/logo/logo.png" rel="icon">
    <title>RuangAdmin - Dashboard</title>
    <link href="{{ asset('vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/ruang-admin.min.css') }}" rel="stylesheet">
    @yield('css')
</head>

<body id="page-top">
    <div id="wrapper">
        @include('layout.sidebar')
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                @include('layout.topbar')
                <!-- Container Fluid-->
                <div class="container-fluid" id="container-wrapper">
                    @yield('breadcrumb')
                    @yield('content')
                    <!-- Modal Logout -->
                    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog"
                        aria-labelledby="exampleModalLabelLogout" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabelLogout">Ohh No!</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p>Are you sure you want to logout?</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-outline-primary"
                                        data-dismiss="modal">Cancel</button>
                                    <a href="login.html" class="btn btn-primary">Logout</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!---Container Fluid-->
            </div>
            @include('layout.footer')
        </div>
    </div>

    <!-- Scroll to top -->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ asset('vendor/jquery-easing/jquery.easing.min.js') }}"></script>
    <script src="{{ asset('js/ruang-admin.min.js') }}"></script>
    @stack('js')
</body>

</html>

resources/views/layout/footer.blade.php
<!-- Footer -->
<div class="row">
    <div class="col-lg-12 text-center">
      <p>Do you like this template ? you can download from <a href="https://github.com/indrijunanda/RuangAdmin"
          class="btn btn-primary btn-sm" target="_blank"><i class="fab fa-fw fa-github"></i>&nbsp;GitHub</a></p>
    </div>
  </div>
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
        <span>copyright &copy; <script> document.write(new Date().getFullYear()); </script> - developed by
            <b><a href="https://indrijunanda.gitlab.io/" target="_blank">indrijunanda</a></b>
        </span>
        </div>
    </div>
</footer>
<!-- Footer -->

resources/views/layout/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url('/') }}">
        <div class="sidebar-brand-icon">
        <img src="img/logo/logo3.png">
        </div>
        <div class="sidebar-brand-text mx-3"></div>
    </a>
    <hr class="sidebar-divider my-0">
    <li class="nav-item active">
        <a class="nav-link" href="{{ url('/') }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>
    <hr class="sidebar-divider">
    <div class="sidebar-heading">
        Fitur
    </div>
    <li class="nav-item">
        <a class="nav-link" href="{{ route('position.index') }}">
            <i class="fas fa-sort-amount-up"></i>
        <span>Jabatan</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ route('employee.index') }}">
            <i class="fas fa-user"></i>
        <span>Karyawan</span>
        </a>
    </li>
    <hr class="sidebar-divider">
    <div class="version" id="version-ruangadmin"></div>
</ul>
<!-- Sidebar -->

resources/views/layout/topbar.blade.php
<!-- TopBar -->
<nav class="navbar navbar-expand navbar-light bg-navbar topbar mb-4 static-top">
    <button id="sidebarToggleTop" class="btn btn-link rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
</nav>
<!-- Topbar -->

resources/views/position.blade.php
@extends('layout.app')

@section('css')
  <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('breadcrumb')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Jabatan</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Jabatan</li>
    </ol>
</div>
@endsection
@section('content')
<div class="card sm mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary"></h6>
    </div>
    <div class="card-body">
        <div class="table-responsive p-3">
            <table class="table align-items-center table-flush" id="dataTable">
              <thead class="thead-light">
                <tr>
                  <th>No.</th>
                  <th>Name</th>
                </tr>
              </thead>
            </table>
          </div>
    </div>
</div>
@endsection

@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script>
    $('#dataTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('position.index') }}",
        columns: [
            { data: 'DT_RowIndex', orderable: false, searchable: false, className: "text-center"},
            { data: 'name' }
        ]
    })
</script>
@endpush